ALL MATHMETICAL OPERATION






In [2]:
import numpy as np

In [3]:
arr_1d=np.array([1,2,3])
print(arr_1d)


[1 2 3]


In [4]:
type(arr_1d)

numpy.ndarray

In [5]:
arr_2d=np.array([[1,2,3],[4,5,6]])
print(arr_2d)

[[1 2 3]
 [4 5 6]]


In [10]:
type(arr_2d)


numpy.ndarray

DIMENTION OF ARRAY

In [7]:
arr_2d.ndim

2

SHAPE OF ARRAY

In [8]:
arr_2d.shape

(2, 3)

SIZE OF ARRAY

In [9]:
arr_2d.size

6

In [13]:
arr_2d.dtype

dtype('int64')