In [4]:
import numpy as np

MATHMETICAL FUNCTION

In [10]:
arr_1 = np.arange(1,10).reshape(3,3)
arr_1


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
arr_2 = np.arange(5,14).reshape(3,3)
arr_2

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

In [11]:
add_value=np.add(arr_1,arr_2)
add_value

array([[ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22]])

In [12]:
sub_val=np.subtract(arr_1,arr_2)
sub_val

array([[-4, -4, -4],
       [-4, -4, -4],
       [-4, -4, -4]])

In [13]:
mul_val=np.multiply(arr_1,arr_2)
mul_val

array([[  5,  12,  21],
       [ 32,  45,  60],
       [ 77,  96, 117]])

In [15]:
index_max=np.argmax(arr_1)
index_max

8

In [16]:
# product of matrix
arr_1 @ arr_2

array([[ 54,  60,  66],
       [126, 141, 156],
       [198, 222, 246]])

In [17]:
# find maximum value
index_min=np.argmin(arr_1)
index_min

0

In [18]:
sum_=np.sum(arr_1)
sum_

45

In [19]:
# sum all value in the column
sum_1=np.sum(arr_1,axis=0)
sum_1

array([12, 15, 18])

In [20]:
# mean value
mean=np.mean(arr_1)
mean

5.0

In [21]:
squart=np.sqrt(arr_1)
squart

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [24]:
exp=np.exp(arr_1)
exp

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [25]:
log=np.log(arr_1)
arr_1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
log_10=np.log10(arr_1)