In [2]:
import numpy as np

arrange function

In [12]:
arr = np.arange(1,13)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

linesapce function

In [13]:
arr_1=np.linspace(1,13,2)
arr_1

array([ 1., 13.])

In [ ]:
1

reshape function

In [15]:
arr_2d=arr.reshape(2,6)
arr_2d

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [17]:
arr_1d=arr_2d.ravel()
arr_1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

max_value

In [19]:
max_=arr_2d.max()
max_

12

min_value

In [21]:
min_=arr_2d.min()
min_

1

In [23]:
max_coll=arr_2d.max(axis=0)
max_coll

array([ 7,  8,  9, 10, 11, 12])

In [24]:
max_row=arr_2d.max(axis=1)
max_row

array([ 6, 12])