In [2]:
import numpy as np

In [4]:
ones_value=np.ones(15)
ones_value

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
ones_value=np.ones((3,5))
ones_value

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

# D_type INTEGER

In [12]:
mx_type=np.ones((3,4),dtype=int)
mx_type

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [9]:
mx_type.dtype

dtype('int64')

In [10]:
mx_type.ndim

2

In [11]:
mx_type.shape

(3, 4)